name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Doxyfile
        run: echo "PROJECT_NAME = Airport\nINPUT = src\nOUTPUT_DIRECTORY = docs" > Doxyfile

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: ./Doxyfile
          working-directory: src
          enable-latex: false  # Cambia a true si necesitas documentación LaTeX

